version: '3.4'
services:
  muon-fees-backend:
    container_name: muon-fees-backend
    image: muon-fees-backend
    restart: always
    build:
      context: .
      network: host

    network_mode: host

    ports:
      - 3002:3002
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - BUILD_MODE=production
